---
- name: Adding Jenkins user
  user: name=jenkins groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Adding Jenkins user to sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%jenkins' line='%jenkins ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Add the Jenkins APT repository key
  apt_key: url=https://pkg.jenkins.io/debian/jenkins.io-2023.key state=present

- name: Add the Jenkins APT repository
  apt_repository: repo="deb https://pkg.jenkins.io/debian binary/" state=present

- name: Install Jenkins
  apt: name={{item}} state=latest
  with_items:
  - jenkins

- name: Configure Jenkins
  template: src=jenkins.j2 dest=/etc/default/jenkins
